# Unit, integration, contract and mutation tests.

.PHONY: test test-go test-dialects cover \
        test-integration test-pact mutation mutation-dry-run

# pkg/security runs a 600k-iteration PBKDF2 derivation per case, which under
# -race takes longer than go test's 10m per-package default.
TEST_TIMEOUT ?= 30m

test: test-go ## Run the engine's tests (same as test-go)

test-go: ## Run Go tests with race detector
	go test -race -count=1 -timeout $(TEST_TIMEOUT) ./...

# What the CI matrix runs, one shard at a time. Serial on purpose: the three
# dialects at once put three containers per package on one machine and the
# resulting contention reads as flakiness rather than as a resource limit.
#
# cmd/lyeve is excluded because it needs modules that are not published.
# cmd/lyeve-core is in, because it builds from this module alone. Keep this
# list in step with ENGINE_PKGS in .github/workflows/ci.yml.
ENGINE_PKGS ?= ./internal/... ./pkg/... ./cmd/lyeve-core/...

# MySQL and MSSQL create and migrate a database per test instead of cloning a
# pre-migrated template, so they need considerably longer than TEST_TIMEOUT.
DIALECT_TEST_TIMEOUT ?= 60m

test-dialects: ## Run the engine suite once per dialect (postgres, mysql, mssql)
	@failed=""; \
	for d in postgres mysql mssql; do \
		echo "$(BOLD)CI_DIALECT=$$d$(RESET)"; \
		CI_DIALECT=$$d go test -count=1 -timeout $(DIALECT_TEST_TIMEOUT) $(ENGINE_PKGS) \
			|| failed="$$failed $$d"; \
	done; \
	if [ -n "$$failed" ]; then \
		echo "$(YELLOW)failed dialects:$$failed$(RESET)"; exit 1; \
	fi
	@echo "$(GREEN)All three dialects green.$(RESET)"

cover: ## Run tests + generate HTML coverage report
	go test -short -race -coverprofile=coverage.out -covermode=atomic -count=1 -timeout $(TEST_TIMEOUT) ./...
	go tool cover -func=coverage.out
	go tool cover -html=coverage.out -o coverage.html
	@echo "open coverage.html to browse line-by-line coverage"

# Tag-guarded trees are compiled by nothing unless a target passes the tag AND
# the path, so this names every tree that holds a tagged file: ./tests/... and
# ./pkg/... both.
#
# TestPluginMigrationRoundtrip is skipped here because it reads plugin
# checkouts named by LYEVE_PLUGIN_TREES, and this target runs from a clone of
# this repository alone.
test-integration: ## Run the tagged integration suite (needs TEST_DATABASE_URL)
	@[ -n "$$TEST_DATABASE_URL" ] || { echo "$(YELLOW)set TEST_DATABASE_URL first - these tests drop tables, so point it at a scratch database$(RESET)"; exit 1; }
	go test -tags=integration -race -count=1 -timeout $(TEST_TIMEOUT) \
		-skip TestPluginMigrationRoundtrip ./tests/... ./pkg/...

# The consumer half of the contract is generated by the admin dashboard, which
# is a separate repo and runs it there. This side verifies the engine still
# satisfies the pacts it publishes, so it needs the server already running.
test-pact: ## Run Pact provider contract tests (needs the API on :3002)
	@echo "$(BOLD)Pact provider contract tests (Go)$(RESET)"
	go test -tags=pact -v -count=1 ./tests/pact/
	@echo "$(GREEN)Pact tests complete.$(RESET)"

# Mutation testing (gremlins)
mutation: ## Run gremlins mutation testing on critical packages (full run)
	@echo "$(BOLD)Mutation testing - gremlins on critical packages$(RESET)"
	@bash scripts/mutation.sh --report
	@echo "$(GREEN)Mutation testing complete.$(RESET)"

mutation-dry-run: ## Dry-run mutation analysis (no test execution, fast)
	@echo "$(BOLD)Mutation analysis - gremlins dry-run$(RESET)"
	@bash scripts/mutation.sh --dry-run
	@echo "$(GREEN)Mutation analysis complete.$(RESET)"
